"""Tests for the Replayer feature.

Includes both unit tests (using JSON fixtures) and E2E tests
(requiring a running Temporal server).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass
from datetime import timedelta
from pathlib import Path
from typing import Any, AsyncIterator

import pytest
import trio

from temporalio_trio import activity, workflow
from temporalio_trio.client import Client
from temporalio_trio.client._workflow_handle import WorkflowHistory
from temporalio_trio.worker import (
    Replayer,
    Worker,
    WorkflowReplayResult,
)


@pytest.fixture
async def trio_client():
    """Create a Trio-based Temporal client for E2E tests."""
    client = await Client.connect("localhost:7233", namespace="default")
    yield client
    await client.close()


# =============================================================================
# Test Workflow Definitions
# =============================================================================


@activity.defn
async def say_hello(name: str) -> str:
    return f"Hello, {name}!"


@workflow.defn
class SayHelloWorkflow:
    """Simple workflow that matches the JSON fixture's SayHelloWorkflow.

    The JSON fixture was generated by the sdk-python test suite with this
    exact workflow type name. The workflow calls the say_hello activity.
    """

    def __init__(self) -> None:
        self._waiting = False
        self._finish = False

    @workflow.run
    async def run(self, params: Any) -> str:
        # Extract name from params (can be SayHelloParams or raw)
        name = params.name if hasattr(params, "name") else str(params)

        result = await workflow.execute_activity(
            say_hello,
            name,
            schedule_to_close_timeout=timedelta(seconds=60),
        )

        # Wait if requested
        if hasattr(params, "should_wait") and params.should_wait:
            self._waiting = True
            await workflow.wait_condition(lambda: self._finish)
            self._waiting = False

        # Raise if requested
        if hasattr(params, "should_error") and params.should_error:
            raise RuntimeError("Intentional error")

        return result

    @workflow.signal
    def finish(self) -> None:
        self._finish = True

    @workflow.query
    def waiting(self) -> bool:
        return self._waiting


@dataclass
class SayHelloParams:
    name: str
    should_wait: bool = False
    should_error: bool = False
    should_cause_nondeterminism: bool = False


# =============================================================================
# Unit Tests (no server required)
# =============================================================================


@pytest.mark.trio
async def test_replayer_workflow_complete_json() -> None:
    """Test replaying a complete workflow from a JSON history fixture."""
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()
    await Replayer(workflows=[SayHelloWorkflow]).replay_workflow(
        WorkflowHistory.from_json("fake", history_json)
    )


@workflow.defn(name="SayHelloWorkflow")
class SayHelloWorkflowNonDet:
    """Modified SayHelloWorkflow that adds extra timer, causing nondeterminism."""

    @workflow.run
    async def run(self, params: Any) -> str:
        name = params.name if hasattr(params, "name") else str(params)
        # Extra timer that doesn't exist in the original history
        await workflow.sleep(0.001)
        result = await workflow.execute_activity(
            say_hello,
            name,
            schedule_to_close_timeout=timedelta(seconds=60),
        )
        return result


@pytest.mark.trio
async def test_replayer_workflow_nondeterministic_json() -> None:
    """Test replaying with a modified workflow that causes nondeterminism."""
    with Path(__file__).with_name(
        "test_replayer_nondeterministic_history.json"
    ).open("r") as f:
        history_json = f.read()
    with pytest.raises(workflow.NondeterminismError):
        await Replayer(workflows=[SayHelloWorkflowNonDet]).replay_workflow(
            WorkflowHistory.from_json("fake", history_json)
        )


@pytest.mark.trio
async def test_replayer_multiple_histories_fail_fast() -> None:
    """Test that replay_workflows stops on first failure with raise_on_replay_failure=True.

    Uses SayHelloWorkflowNonDet which adds an extra timer, causing nondeterminism
    with the standard history.
    """
    with Path(__file__).with_name(
        "test_replayer_nondeterministic_history.json"
    ).open("r") as f:
        history_json_bad = f.read()
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()

    callcount = 0

    async def histories() -> AsyncIterator[WorkflowHistory]:
        nonlocal callcount
        callcount += 1
        yield WorkflowHistory.from_json("fake_bad", history_json_bad)
        # Small sleep so the async iterator can be interrupted
        await trio.sleep(0.1)
        callcount += 1
        yield WorkflowHistory.from_json("fake", history_json)

    with pytest.raises(workflow.NondeterminismError):
        await Replayer(
            workflows=[SayHelloWorkflowNonDet]
        ).replay_workflows(histories())

    # We should only have replayed the first history since we fail fast
    assert callcount == 1


@pytest.mark.trio
async def test_replayer_multiple_histories_fail_slow() -> None:
    """Test that replay_workflows continues on failure with raise_on_replay_failure=False.

    Uses SayHelloWorkflowNonDet for the bad history (causing nondeterminism)
    and the normal SayHelloWorkflow definition is also registered but with
    the nondet version to test that the replayer catches the error and continues.
    """
    with Path(__file__).with_name(
        "test_replayer_nondeterministic_history.json"
    ).open("r") as f:
        history_json_bad = f.read()
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()

    bad_hist = WorkflowHistory.from_json("fake_bad", history_json_bad)
    bad_hist_run_id = bad_hist.events[
        0
    ].workflow_execution_started_event_attributes.original_execution_run_id

    callcount = 0

    async def histories() -> AsyncIterator[WorkflowHistory]:
        nonlocal callcount
        callcount += 1
        yield bad_hist
        callcount += 1
        yield WorkflowHistory.from_json("fake", history_json)
        callcount += 1
        h3 = WorkflowHistory.from_json("fake", history_json)
        # Give a new run id so replay continues
        h3.events[
            0
        ].workflow_execution_started_event_attributes.original_execution_run_id = (
            "r3"
        )
        h3.events[
            0
        ].workflow_execution_started_event_attributes.first_execution_run_id = (
            "r3"
        )
        yield h3
        callcount += 1

    results = await Replayer(
        workflows=[SayHelloWorkflowNonDet]
    ).replay_workflows(histories(), raise_on_replay_failure=False)

    assert callcount == 4
    assert results.replay_failures
    assert results.replay_failures[bad_hist_run_id] is not None


def test_replayer_no_workflows_raises() -> None:
    """Test that Replayer raises if no workflows are provided."""
    with pytest.raises(ValueError, match="At least one workflow"):
        Replayer(workflows=[])


def test_replayer_config() -> None:
    """Test that Replayer.config() returns a copy of the configuration."""
    replayer = Replayer(
        workflows=[SayHelloWorkflow],
        namespace="test-ns",
    )
    config = replayer.config()
    assert config["namespace"] == "test-ns"
    assert SayHelloWorkflow in config["workflows"]
    # Ensure it's a copy
    config["namespace"] = "modified"
    assert replayer.config()["namespace"] == "test-ns"


# =============================================================================
# WorkflowHistory Tests
# =============================================================================


def test_workflow_history_from_json() -> None:
    """Test WorkflowHistory.from_json parses correctly."""
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()

    history = WorkflowHistory.from_json("test-wf-id", history_json)
    assert history.workflow_id == "test-wf-id"
    assert len(history.events) > 0
    # run_id should be extractable
    run_id = history.run_id
    assert isinstance(run_id, str)
    assert len(run_id) > 0


def test_workflow_history_to_json() -> None:
    """Test WorkflowHistory round-trip through JSON."""
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()

    history = WorkflowHistory.from_json("test-wf-id", history_json)
    json_str = history.to_json()
    assert isinstance(json_str, str)
    assert "events" in json_str

    # Round-trip: from_json -> to_json -> from_json should preserve events
    history2 = WorkflowHistory.from_json("test-wf-id-2", json_str)
    assert len(history2.events) == len(history.events)


def test_workflow_history_to_json_dict() -> None:
    """Test WorkflowHistory.to_json_dict returns a dict."""
    with Path(__file__).with_name(
        "test_replayer_complete_history.json"
    ).open("r") as f:
        history_json = f.read()

    history = WorkflowHistory.from_json("test-wf-id", history_json)
    json_dict = history.to_json_dict()
    assert isinstance(json_dict, dict)
    assert "events" in json_dict


def test_workflow_history_run_id_empty_raises() -> None:
    """Test that accessing run_id on empty history raises."""
    history = WorkflowHistory(workflow_id="test", events=[])
    with pytest.raises(RuntimeError, match="No events"):
        _ = history.run_id


# =============================================================================
# E2E Tests (require Temporal server)
# =============================================================================


@workflow.defn
class SimpleE2EWorkflow:
    """Simple workflow for E2E replay testing."""

    @workflow.run
    async def run(self, name: str) -> str:
        await workflow.sleep(0.1)
        return f"Hello, {name}!"


@workflow.defn(name="SimpleE2EWorkflow")
class SimpleE2EWorkflowModified:
    """Modified version to trigger nondeterminism on replay.

    Uses the same Temporal name as SimpleE2EWorkflow to allow replaying
    the original workflow's history with this modified code.
    """

    @workflow.run
    async def run(self, name: str) -> str:
        # Different code path - extra sleep causes nondeterminism during replay
        await workflow.sleep(0.1)
        await workflow.sleep(0.2)
        return f"Hello, {name}!"


@pytest.mark.temporal_server
@pytest.mark.trio
async def test_replayer_e2e_complete_workflow(
    trio_client: Any,
) -> None:
    """E2E: Run workflow, fetch history, replay successfully."""
    task_queue = f"replay-e2e-{uuid.uuid4()}"
    workflow_id = f"replay-wf-{uuid.uuid4()}"

    # Run the workflow using a nursery-managed worker
    async with trio.open_nursery() as nursery:
        w = Worker(
            trio_client,
            task_queue=task_queue,
            workflows=[SimpleE2EWorkflow],
        )
        nursery.start_soon(w.run)

        handle = await trio_client.start_workflow(
            "SimpleE2EWorkflow",
            "Temporal",
            id=workflow_id,
            task_queue=task_queue,
        )
        result = await handle.result(timeout=15)
        assert result == "Hello, Temporal!"

        # Shutdown worker
        await w.shutdown()
        nursery.cancel_scope.cancel()

    # Fetch history and replay
    history = await handle.fetch_history()
    await Replayer(workflows=[SimpleE2EWorkflow]).replay_workflow(history)


@pytest.mark.temporal_server
@pytest.mark.trio
async def test_replayer_e2e_nondeterminism(
    trio_client: Any,
) -> None:
    """E2E: Run workflow, replay with modified code -> nondeterminism detected."""
    task_queue = f"replay-e2e-nondet-{uuid.uuid4()}"
    workflow_id = f"replay-nondet-{uuid.uuid4()}"

    # Run the workflow
    async with trio.open_nursery() as nursery:
        w = Worker(
            trio_client,
            task_queue=task_queue,
            workflows=[SimpleE2EWorkflow],
        )
        nursery.start_soon(w.run)

        handle = await trio_client.start_workflow(
            "SimpleE2EWorkflow",
            "Temporal",
            id=workflow_id,
            task_queue=task_queue,
        )
        result = await handle.result(timeout=15)
        assert result == "Hello, Temporal!"

        await w.shutdown()
        nursery.cancel_scope.cancel()

    # Fetch history and replay with modified workflow -> nondeterminism
    history = await handle.fetch_history()
    with pytest.raises(workflow.NondeterminismError):
        await Replayer(
            workflows=[SimpleE2EWorkflowModified]
        ).replay_workflow(history)
