"""Workflow state tracking for the single-threaded worker.

This module provides the WorkflowState dataclass which tracks state for a running
workflow in the single `trio.run()` execution model. Each workflow gets its own
WorkflowState instance that manages activation delivery and command collection.

This implements Phase 3 of the single-threaded migration plan.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import trio

if TYPE_CHECKING:
    from temporalio_trio.worker._activation import WorkflowActivation
    from temporalio_trio.worker._runtime import WorkflowRuntime

__all__ = ["WorkflowState"]


@dataclass
class WorkflowState:
    """Tracks state for a running workflow in the single-threaded worker.

    This class manages the communication between the dispatcher and a workflow task:
    - The dispatcher delivers activations via `deliver_activation()`
    - The workflow task waits for activations via `wait_for_activation()`
    - The workflow task signals command readiness via `signal_commands_ready()`
    - The dispatcher waits for commands via `wait_for_commands()`

    The flow is:
    1. Dispatcher receives activation from bridge
    2. Dispatcher calls `deliver_activation()` (sets event)
    3. Workflow task wakes up and processes activation
    4. Workflow task calls `signal_commands_ready()` (sets event)
    5. Dispatcher wakes up and reads commands via `wait_for_commands()`
    6. Dispatcher sends completion to bridge

    Attributes:
        run_id: Unique identifier for this workflow run.
        runtime: The WorkflowRuntime instance for this workflow (set after creation).
        pending_activation: The activation waiting to be processed by the workflow.
        activation_event: Event to signal that an activation is ready.
        commands_ready: Event to signal that commands are ready to be collected.
    """

    run_id: str
    """Unique identifier for this workflow run."""

    runtime: WorkflowRuntime | None = None
    """The WorkflowRuntime instance for this workflow."""

    pending_activation: WorkflowActivation | None = None
    """The activation waiting to be processed by the workflow."""

    # Note: trio.Event cannot have a default_factory in dataclass because it requires
    # the Trio context to be active. We initialize these in __post_init__.
    activation_event: trio.Event = field(default_factory=trio.Event)
    """Event to signal that an activation is ready."""

    commands_ready: trio.Event = field(default_factory=trio.Event)
    """Event to signal that commands are ready to be collected."""

    # Completion state
    is_complete: bool = False
    """Whether the workflow has completed (success, failure, or cancelled)."""

    completion_result: Any = None
    """The result of the workflow execution (stored for replay without re-execution)."""

    def deliver_activation(self, activation: WorkflowActivation) -> None:
        """Deliver an activation to the workflow task.

        This stores the activation and signals the workflow task to wake up.
        Should be called by the dispatcher when an activation is received.

        Args:
            activation: The activation to deliver.
        """
        self.pending_activation = activation
        self.activation_event.set()

    async def wait_for_activation(self) -> WorkflowActivation:
        """Wait for the next activation to be delivered.

        Should be called by the workflow task to wait for work.

        Returns:
            The delivered activation.

        Raises:
            RuntimeError: If no activation is available after event is set.
        """
        await self.activation_event.wait()
        # Reset the event for the next activation
        self.activation_event = trio.Event()

        activation = self.pending_activation
        if activation is None:
            raise RuntimeError("Activation event was set but no activation available")
        self.pending_activation = None
        return activation

    def signal_commands_ready(self) -> None:
        """Signal that commands are ready to be collected.

        Should be called by the workflow task after processing an activation.
        """
        self.commands_ready.set()

    async def wait_for_commands(self) -> list[Any]:
        """Wait for commands to be ready and return them.

        Should be called by the dispatcher after delivering an activation.
        This waits for the workflow task to signal completion of processing
        and then collects the commands from the runtime.

        Returns:
            List of commands generated by the workflow.

        Raises:
            RuntimeError: If runtime is not set.
        """
        await self.commands_ready.wait()
        # Reset the event for the next activation
        self.commands_ready = trio.Event()

        if self.runtime is None:
            raise RuntimeError("Runtime not set on WorkflowState")

        # Get commands from the runtime and clear them
        commands = list(self.runtime.commands)
        self.runtime.commands.clear()
        return commands

    def mark_complete(self) -> None:
        """Mark the workflow as complete.

        Should be called when the workflow finishes execution (success, failure,
        or cancellation).
        """
        self.is_complete = True
